
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DOCTYPE FIN IDENTIFICADOR MAYOR MENOR RESERVADAstatement : MENOR RESERVADA DOCTYPE DOCTYPE MAYOR MENOR IDENTIFICADOR MAYOR MENOR IDENTIFICADOR MAYOR MENOR IDENTIFICADOR MAYOR RESERVADA RESERVADA RESERVADA MENOR FIN IDENTIFICADOR MAYOR MENOR FIN IDENTIFICADOR MAYOR MENOR IDENTIFICADOR MAYOR MENOR IDENTIFICADOR MAYOR RESERVADA RESERVADA RESERVADA MENOR FIN IDENTIFICADOR MAYOR MENOR FIN IDENTIFICADOR MAYOR MENOR FIN IDENTIFICADOR MAYOR'
    
_lr_action_items = {'MENOR':([0,6,9,12,18,22,26,29,35,39,43,],[2,7,10,13,19,23,27,30,36,40,44,]),'$end':([1,47,],[0,-1,]),'RESERVADA':([2,15,16,17,32,33,34,],[3,16,17,18,33,34,35,]),'DOCTYPE':([3,4,],[4,5,]),'MAYOR':([5,8,11,14,21,25,28,31,38,42,46,],[6,9,12,15,22,26,29,32,39,43,47,]),'IDENTIFICADOR':([7,10,13,20,24,27,30,37,41,45,],[8,11,14,21,25,28,31,38,42,46,]),'FIN':([19,23,36,40,44,],[20,24,37,41,45,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> MENOR RESERVADA DOCTYPE DOCTYPE MAYOR MENOR IDENTIFICADOR MAYOR MENOR IDENTIFICADOR MAYOR MENOR IDENTIFICADOR MAYOR RESERVADA RESERVADA RESERVADA MENOR FIN IDENTIFICADOR MAYOR MENOR FIN IDENTIFICADOR MAYOR MENOR IDENTIFICADOR MAYOR MENOR IDENTIFICADOR MAYOR RESERVADA RESERVADA RESERVADA MENOR FIN IDENTIFICADOR MAYOR MENOR FIN IDENTIFICADOR MAYOR MENOR FIN IDENTIFICADOR MAYOR','statement',46,'p_statement_main','app.py',42),
]
